<?php
/**
 * Created by PhpStorm.
 * User: ubuntu
 * Date: 21/12/18
 * Time: 11:14
 */

/**
 * Implements hook_user_login().
 */

use Symfony\Component\HttpFoundation\RedirectResponse;

function arb_misc_user_login($account) {
  // Si le user est membre d'une région, on le redirige vers sa région
  if ($region_id = $account->get('field_region')->getString()) {
    $response = new RedirectResponse('/group/' . $region_id);
    $response->send();
  }
  // sinon vers la page d'accueil.
  else {
    $response = new RedirectResponse('/');
    $response->send();
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function arb_misc_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // On enlève le champ non obligatoire "Membre du quatuor" du formulatire d'inscription.
  unset($form['field_quatuor_member']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function arb_misc_form_user_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // ----- Affichage du champ "Membre du quatuor" réservé aux admins drupal ou aux admin de groupe -----
  // 1 - On récupère les roles drupal de l'utilisateur courant
  $current_user = \Drupal::currentUser();
  // Attention, l'enregistrement d'un utilisateur passe aussi par ce hook.
  // Donc, il faut vérfier que l'internaute est connecté pour continuer,
  // sinon WSOD -> "The website encountered an unexpected error. Please try again later."
  if (!$current_user->id()) {
    return;
  }

  $current_user_drupal_roles = $current_user->getRoles();
  // 2 - On récupère les roles Group de l'utilisateur courant.
  // Pour cela, on récupère ses adhésions Group (on obtient un tableau d'adhésions).
  $current_user_memberships = \Drupal::service('group.membership_loader')
    ->loadByUser($current_user);
  // Dans le cas de ARB, un user ne peut appartenir qu'à un seul groupe donc c'est forcément à l'index 0 du tableau.
  $current_user_group_roles = $current_user_memberships[0]->getRoles();

  $current_user_all_roles = array_merge($current_user_drupal_roles, array_keys($current_user_group_roles));
  $allowed_roles = array(
    'administrator',
    'regional_group-administrator',
    'national_group_administrator'
  );

  if ($current_user->id() != 1 && !array_intersect($allowed_roles, $current_user_all_roles)) {
    unset($form['field_quatuor_member']);
  }
}

/**
 * Implements hook_node_access().
 */
function arb_misc_node_access(\Drupal\node\NodeInterface $node, $op, \Drupal\Core\Session\AccountInterface $account) {
  if ('news' == $node->getType() && !$account->id()) {
    return \Drupal\Core\Access\AccessResult::forbidden();
  }
}


/**
 * Implements hook_theme().
 */
function arb_misc_theme($existing, $type, $theme, $path) {
  return [
    'backlink__block' => [
      'variables' => [
        'backlink' => NULL,
      ],
    ],
  ];
}
